// Compact country list for the signup dropdown (name + flag emoji).
// Extend freely — the value stored is the country name.
export const COUNTRIES: { name: string; flag: string }[] = [
  { name: "Togo", flag: "🇹🇬" },
  { name: "Benin", flag: "🇧🇯" },
  { name: "Burkina Faso", flag: "🇧🇫" },
  { name: "Côte d'Ivoire", flag: "🇨🇮" },
  { name: "Ghana", flag: "🇬🇭" },
  { name: "Nigeria", flag: "🇳🇬" },
  { name: "Niger", flag: "🇳🇪" },
  { name: "Senegal", flag: "🇸🇳" },
  { name: "Mali", flag: "🇲🇱" },
  { name: "Guinea", flag: "🇬🇳" },
  { name: "Cameroon", flag: "🇨🇲" },
  { name: "Gabon", flag: "🇬🇦" },
  { name: "Congo", flag: "🇨🇬" },
  { name: "DR Congo", flag: "🇨🇩" },
  { name: "Kenya", flag: "🇰🇪" },
  { name: "Ethiopia", flag: "🇪🇹" },
  { name: "Tanzania", flag: "🇹🇿" },
  { name: "Uganda", flag: "🇺🇬" },
  { name: "Rwanda", flag: "🇷🇼" },
  { name: "South Africa", flag: "🇿🇦" },
  { name: "Morocco", flag: "🇲🇦" },
  { name: "Algeria", flag: "🇩🇿" },
  { name: "Tunisia", flag: "🇹🇳" },
  { name: "Egypt", flag: "🇪🇬" },
  { name: "France", flag: "🇫🇷" },
  { name: "Belgium", flag: "🇧🇪" },
  { name: "Switzerland", flag: "🇨🇭" },
  { name: "United Kingdom", flag: "🇬🇧" },
  { name: "Germany", flag: "🇩🇪" },
  { name: "Spain", flag: "🇪🇸" },
  { name: "Italy", flag: "🇮🇹" },
  { name: "Portugal", flag: "🇵🇹" },
  { name: "Netherlands", flag: "🇳🇱" },
  { name: "Luxembourg", flag: "🇱🇺" },
  { name: "Monaco", flag: "🇲🇨" },
  { name: "United States", flag: "🇺🇸" },
  { name: "Canada", flag: "🇨🇦" },
  { name: "Brazil", flag: "🇧🇷" },
  { name: "United Arab Emirates", flag: "🇦🇪" },
  { name: "Saudi Arabia", flag: "🇸🇦" },
  { name: "India", flag: "🇮🇳" },
  { name: "China", flag: "🇨🇳" },
  { name: "Japan", flag: "🇯🇵" },
  { name: "Australia", flag: "🇦🇺" },
  { name: "Other", flag: "🌍" },
].sort((a, b) => a.name.localeCompare(b.name));
